apiVersion: nais.io/v1
kind: Alert
metadata:
  labels:
    app: security-playbook
    team: security-champion-admin
  name: security-playbook
  namespace: security-champion-admin
spec:
  alerts:
    - alert: Antall restarts
      expr: sum(increase(kube_pod_container_status_restarts_total{container=~"security-playbook"}[30m])) by (container) > 3
      for: 5m
      action: Se `kubectl describe pod security-playbook` for events, og `kubectl logs -l app=security-playbook` for logger
      description: "security-playbook har restartet flere ganger siste halvtimen!"
      severity: danger
    - alert: Ingen tilgjengelig podder
      expr: kube_deployment_status_replicas_available{deployment="security-playbook"} == 0
      for: 2m
      description: "App security-playbook er nede i namespace security-champion-admin. Ingen tilgjengelige podder."
      action: Se `kubectl get  pod -l app=security-playbook` for status på podder, og `kubectl logs -l app=security-playbook` for logger.
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="security-playbook",log_level=~"Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="security-playbook"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app security-playbook i namespace security-champion-admin, for å se hvorfor det er så mye feil"
  receivers:
    slack:
      channel: security-champions-playbook-aktivitet
      prependText: '<!here> | '
    enabled: true
