name: Build and deploy main
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # ratchet:actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Cache dependencies
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # ratchet:actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload to CDN
        id: upload
        uses: navikt/frontend/actions/spa-deploy/v1@main
        with:
          team-name: security-champion-admin
          app-name: security-playbook
          source: ./build
          ingress: https://playbooktest.nav.no/
          nais-deploy-apikey: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
        shell: bash
  